In [1]:
import sys
import numpy as np
import random
import copy

random.seed(10)

# mbnpy toolkit
sys.path.append(r"C:\Users\jb622s\git\BNS-JT\BNS_JT") 
from BNS_JT import cpm, variable

# Problem
<figure>
<img src="img/house_power_prob.png" style="width:400px">
</figure>

# Modelling

## Hazard scenarios

In [2]:
cpms={}
vars={}

vars['haz'] = variable.Variable( name='haz', values=['mild','medi','inte'] ) # values=(mild, medium, intense)
cpms['haz'] = cpm.Cpm( variables=[vars['haz']], no_child=1, C=np.array([0,1,2]), p=[0.5,0.2,0.3] )

print(vars['haz'])
print(cpms['haz'])


"Variable(name=haz, B=[{0}, {1}, {2}, {0, 1}, {0, 2}, {1, 2}, {0, 1, 2}], values=['mild', 'medi', 'inte'])"
Cpm(variables=['haz'], no_child=1, C=[[0]
 [1]
 [2]], p=[[0.5]
 [0.2]
 [0.3]]


## Structural daamage

In [3]:
# Substations
n_subs = 2
for i in range(n_subs):
    name = 'xs' + str(i)
    vars[name] = variable.Variable( name=name, values=['fail','surv'] ) # values=(failure, survival)
    cpms[name] = cpm.Cpm( variables = [vars[name], vars['haz']], no_child = 1,
                      C=np.array([[0,0], [1,0], [0,1], [1,1], [0,2], [1,2]]) )

cpms['xs0'].p = np.array([0.001, 0.999, 0.01, 0.99, 0.1, 0.9])
cpms['xs1'].p = np.array([0.005, 0.995, 0.05, 0.95, 0.2, 0.8])

# Poles
n_pole = 8
for i in range(n_pole):
    name = 'xp' + str(i)
    vars[name] = variable.Variable( name=name, values=['fail','surv'] ) # values=(failure, survival)
    cpms[name] = cpm.Cpm( variables = [vars[name], vars['haz']], no_child = 1,
                      C=np.array([[0,0], [1,0], [0,1], [1,1], [0,2], [1,2]]) )
    
    if i in [0,2,4,6]:
        cpms[name].p = np.array([0.001, 0.999, 0.01, 0.99, 0.1, 0.9])
    else:
        cpms[name].p = np.array([0.005, 0.995, 0.05, 0.95, 0.2, 0.8])


## Downtime

In [4]:
max_ct = n_subs + n_pole 
rep_pri = ['xs' + str(i) for i in range(n_subs)] + ['xp' + str(i) for i in range(n_pole)] # repair priority

print(rep_pri)


['xs0', 'xs1', 'xp0', 'xp1', 'xp2', 'xp3', 'xp4', 'xp5', 'xp6', 'xp7']


In [5]:
for i, x in enumerate(rep_pri):
    name = 't'+x[1:]
    vars[name] = variable.Variable( name=name, values=list(range(i+2)) )

    if i < 1: # first element
        cpms[name] = cpm.Cpm( variables = [vars[name], vars[x]], no_child = 1, C=np.array([[1,0], [0, 1]]), p=np.array([1,1]) )
    else:
        t_old_vars = vars[t_old].values

        Cx = np.empty(shape=(0,3), dtype=int)
        for v in t_old_vars:
            Cx_new = [[v, 1, v], [v+1, 0, v]]
            Cx = np.vstack( [Cx, Cx_new] )

        cpms[name] = cpm.Cpm( variables = [vars[name], vars[x], vars[t_old]], no_child = 1, C=Cx, p=np.ones(shape=(2*len(t_old_vars)), dtype=np.float32) )

    t_old = copy.deepcopy(name)


print(vars['ts0'])
print(cpms['ts0'])
print(" ")
print(vars['tp3'])
print(cpms['tp3'])

'Variable(name=ts0, B=[{0}, {1}, {0, 1}], values=[0, 1])'
Cpm(variables=['ts0', 'xs0'], no_child=1, C=[[1 0]
 [0 1]], p=[[1]
 [1]]
 
'Variable(name=tp3, B=[{0}, {1}, {2}, {3}, {4}, {5}, {6}, {0, 1}, {0, 2}, {0, 3}, {0, 4}, {0, 5}, {0, 6}, {1, 2}, {1, 3}, {1, 4}, {1, 5}, {1, 6}, {2, 3}, {2, 4}, {2, 5}, {2, 6}, {3, 4}, {3, 5}, {3, 6}, {4, 5}, {4, 6}, {5, 6}, {0, 1, 2}, {0, 1, 3}, {0, 1, 4}, {0, 1, 5}, {0, 1, 6}, {0, 2, 3}, {0, 2, 4}, {0, 2, 5}, {0, 2, 6}, {0, 3, 4}, {0, 3, 5}, {0, 3, 6}, {0, 4, 5}, {0, 4, 6}, {0, 5, 6}, {1, 2, 3}, {1, 2, 4}, {1, 2, 5}, {1, 2, 6}, {1, 3, 4}, {1, 3, 5}, {1, 3, 6}, {1, 4, 5}, {1, 4, 6}, {1, 5, 6}, {2, 3, 4}, {2, 3, 5}, {2, 3, 6}, {2, 4, 5}, {2, 4, 6}, {2, 5, 6}, {3, 4, 5}, {3, 4, 6}, {3, 5, 6}, {4, 5, 6}, {0, 1, 2, 3}, {0, 1, 2, 4}, {0, 1, 2, 5}, {0, 1, 2, 6}, {0, 1, 3, 4}, {0, 1, 3, 5}, {0, 1, 3, 6}, {0, 1, 4, 5}, {0, 1, 4, 6}, {0, 1, 5, 6}, {0, 2, 3, 4}, {0, 2, 3, 5}, {0, 2, 3, 6}, {0, 2, 4, 5}, {0, 2, 4, 6}, {0, 2, 5, 6}, {0, 3, 4, 5}, {0, 3, 4, 6}, {0, 

## Power cut time

In [6]:
def get_C_max_val( vars_p ):

    def get_mv( var ): # get maximum values
        return max(var.values)
    
    vars_p.sort(key=get_mv) # sort variables with a lower maximum value (to minimise # of C's rows)

    C_new = np.empty(shape=(0,1+len(vars_p)), dtype='int32') # var: [X] + vars_p
    vals_new = []
    for i, p in enumerate(vars_p):
        vs_p = copy.deepcopy( vars_p[i].values )
        vs_p.sort()
        
        for v in vs_p:
            c_i = np.zeros(shape=(1,1+len(vars_p)), dtype='int32')
            c_i[0][i+1] = p.values.index(v)

            add = True
            for i2, p2 in enumerate(vars_p):
                if i != i2:
                    if i2 < i:
                        vs_i2 = {y for y, z in enumerate(p2.values) if z < v}

                    if i2 > i:
                        vs_i2 = {y for y, z in enumerate(p2.values) if z <= v}
                        

                    if len(vs_i2) < 1:
                        add = False
                        break
                    else:
                        st_i2 = p2.B.index(vs_i2)
                        c_i[0][i2+1] = st_i2

            if add:
                if v not in vals_new:
                    vals_new.append(v)
                c_i[0][0] = vals_new.index(v)
                C_new = np.vstack([C_new, c_i])

    return C_new, vals_new

In [7]:
# Example 1
vars_p_h0 = [vars['tp0'], vars['ts0']]
C_h0, vals_h0 = get_C_max_val(vars_p_h0)

print(C_h0, vals_h0)

# Example 2
vars_p_h1 = [vars['tp1'], vars['tp0'], vars['ts0']]
C_h1, vals_h1 = get_C_max_val(vars_p_h1)

print(C_h1, vals_h1)

[[0 0 0]
 [1 1 4]
 [1 0 1]
 [2 2 2]
 [3 2 3]] [0, 1, 2, 3]
[[ 0  0  0  0]
 [ 1  1  4  5]
 [ 1  0  1  5]
 [ 2  2  2 15]
 [ 3  2  3 25]
 [ 1  0  0  1]
 [ 2  2  4  2]
 [ 3  2 10  3]
 [ 4  2 14  4]] [0, 1, 2, 3, 4]


In [8]:
def get_C_min_val( vars_p ):

    def get_mv( var ): # get maximum values
        return max(var.values)
    
    vars_p.sort(key=get_mv) # sort variables with a lower maximum value (to minimise # of C's rows)

    C_new = np.empty(shape=(0,1+len(vars_p)), dtype='int32') # var: [X] + vars_p
    vals_new = []
    for i, p in enumerate(vars_p):
        vs_p = copy.deepcopy( vars_p[i].values )
        vs_p.sort()
        
        for v in vs_p:
            c_i = np.zeros(shape=(1,1+len(vars_p)), dtype='int32')
            c_i[0][i+1] = p.values.index(v)

            add = True
            for i2, p2 in enumerate(vars_p):
                if i != i2:
                    if i2 < i:
                        vs_i2 = {y for y, z in enumerate(p2.values) if z > v}

                    if i2 > i:
                        vs_i2 = {y for y, z in enumerate(p2.values) if z >= v}
                        

                    if len(vs_i2) < 1:
                        add = False
                        break
                    else:
                        st_i2 = p2.B.index(vs_i2)
                        c_i[0][i2+1] = st_i2

            if add:
                if v not in vals_new:
                    vals_new.append(v)
                c_i[0][0] = vals_new.index(v)
                C_new = np.vstack([C_new, c_i])

    return C_new, vals_new

In [9]:
# Example 1
vars_p_h0 = [vars['tp0'], vars['ts0']]
C_h0, vals_h0 = get_C_min_val(vars_p_h0)

print(C_h0, vals_h0)

# Example 2
vars_p_h1 = [vars['tp1'], vars['tp0'], vars['ts0']]
C_h1, vals_h1 = get_C_min_val(vars_p_h1)

print(C_h1, vals_h1)

[[ 0  0 14]
 [ 1  1 13]
 [ 0  1  0]] [0, 1]
[[ 0  0 14 30]
 [ 1  1 13 29]
 [ 0  1  0 30]
 [ 0  1 13  0]] [0, 1]


In [10]:
cut_lin = {} # cut-set of link-sets for each house

cut_lin['h0'] = [['ts0', 'tp0']]
cut_lin['h1'] = [['ts0', 'tp0', 'tp1']]
cut_lin['h2'] = [['ts0', 'tp2']]
cut_lin['h3'] = [['ts0', 'tp2', 'tp3'], ['ts1','tp4']]
cut_lin['h4'] = [['ts0', 'tp2', 'tp3', 'tp5'], ['ts1', 'tp4','tp5']]
cut_lin['h5'] = [['ts1','tp6']]
cut_lin['h6'] = [['ts1','tp6', 'tp7']]

for h, sets in cut_lin.items():
    if len(sets) == 1:              
        vars_h = [vars[x] for x in sets[0]]

        C_h, vals_h = get_C_max_val( vars_h )
        vars[h] = variable.Variable( name=h, values=vals_h )
        cpms[h] = cpm.Cpm( variables=[vars[h]] + vars_h, no_child=1, C=C_h, p=np.ones(shape=(len(C_h),1), dtype='float64') )

    else:
        names_hs = [h+str(i) for i in range(len(sets))]
        for h_i, s_i in zip(names_hs, sets):
            vars_h_i = [vars[x] for x in s_i]

            C_h_i, vals_h_i = get_C_max_val( vars_h_i )
            vars[h_i] = variable.Variable( name=h_i, values=vals_h_i )
            cpms[h_i] = cpm.Cpm( variables=[vars[h_i]] + vars_h_i, no_child=1, C=C_h_i, p=np.ones(shape=(len(C_h_i),1), dtype='float64') )

        vars_hs = [vars[n] for n in names_hs]
        C_h, vals_h = get_C_min_val( vars_hs )
        vars[h] = variable.Variable( name=h, values=vals_h )
        cpms[h] = cpm.Cpm( variables=[vars[h]] + vars_hs, no_child=1, C=C_h, p=np.ones(shape=(len(C_h),1), dtype='float64') )


In [11]:
print(vars['h1'])
print(cpms['h1'])

print(vars['h3'])
print(cpms['h3'])

print(vars['h30'])
print(cpms['h30'])

'Variable(name=h1, B=[{0}, {1}, {2}, {3}, {4}, {0, 1}, {0, 2}, {0, 3}, {0, 4}, {1, 2}, {1, 3}, {1, 4}, {2, 3}, {2, 4}, {3, 4}, {0, 1, 2}, {0, 1, 3}, {0, 1, 4}, {0, 2, 3}, {0, 2, 4}, {0, 3, 4}, {1, 2, 3}, {1, 2, 4}, {1, 3, 4}, {2, 3, 4}, {0, 1, 2, 3}, {0, 1, 2, 4}, {0, 1, 3, 4}, {0, 2, 3, 4}, {1, 2, 3, 4}, {0, 1, 2, 3, 4}], values=[0, 1, 2, 3, 4])'
Cpm(variables=['h1', 'ts0', 'tp0', 'tp1'], no_child=1, C=[[ 0  0  0  0]
 [ 1  1  4  5]
 [ 1  0  1  5]
 [ 2  2  2 15]
 [ 3  2  3 25]
 [ 1  0  0  1]
 [ 2  2  4  2]
 [ 3  2 10  3]
 [ 4  2 14  4]], p=[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
'Variable(name=h3, B=[{0}, {1}, {2}, {3}, {4}, {5}, {6}, {0, 1}, {0, 2}, {0, 3}, {0, 4}, {0, 5}, {0, 6}, {1, 2}, {1, 3}, {1, 4}, {1, 5}, {1, 6}, {2, 3}, {2, 4}, {2, 5}, {2, 6}, {3, 4}, {3, 5}, {3, 6}, {4, 5}, {4, 6}, {5, 6}, {0, 1, 2}, {0, 1, 3}, {0, 1, 4}, {0, 1, 5}, {0, 1, 6}, {0, 2, 3}, {0, 2, 4}, {0, 2, 5}, {0, 2, 6}, {0, 3, 4}, {0, 3, 5}, {0, 3, 6}, {0, 4, 5}, {0, 4, 6}, {0, 5, 6}, {1, 2, 3}

# Inference

In [26]:
def get_inf_vars( vars_star, cpms, VE_ord = None ):

    """
    INPUT:
    - vars_star: a list of variable names, whose marginal distributions are of interest
    - cpms: a list of CPMs
    - VE_ord (optional): a list of variable names, representing a VE order. The output list of vars_inf is sorted accordingly.
    """

    vars_inf = [] # relevant variables for inference
    vars_inf_new = vars_star
    while len(vars_inf_new) > 0:
        v1 = copy.deepcopy( vars_inf_new[0] )
        vars_inf_new.remove(v1)
        vars_inf.append(v1)

        v1_sco = [x.name for x in cpms[v1].variables] # Scope of v1
        for p in v1_sco:
            if p not in vars_inf and p not in vars_inf_new:
                vars_inf_new.append(p)

    if VE_ord is not None:
        def get_ord_inf( x, VE_ord ):
            return VE_ord.index(x) 
        
        vars_inf.sort( key=(lambda x: get_ord_inf(x, VE_ord)) )

    return vars_inf

In [27]:
n_hou = len(cut_lin)

VE_ord= ['haz'] + ['xs'+str(i) for i in range(n_subs)] + ['xp'+str(i) for i in range(n_pole)] + \
        ['ts'+str(i) for i in range(n_subs)] + ['tp'+str(i) for i in range(n_pole)] + \
        ['h'+str(i) for i in range(n_hou)]

# Example 1
h_star1 = ['h0']
vars_inf1 = get_inf_vars( h_star1, cpms, VE_ord )
print(vars_inf1)

# Example 2
h_star2 = ['h0','h1']
vars_inf2 = get_inf_vars( h_star2, cpms, VE_ord )
print(vars_inf2)

['haz', 'xs0', 'xs1', 'xp0', 'ts0', 'ts1', 'tp0', 'h0']
['haz', 'xs0', 'xs1', 'xp0', 'xp1', 'ts0', 'ts1', 'tp0', 'tp1', 'h0', 'h1']


In [136]:
print([cpms[v] for v in cond_vars])

[Cpm(variables=['haz'], no_child=1, C=[[0]
 [1]
 [2]], p=[[0.5]
 [0.2]
 [0.3]], Cpm(variables=['xs0', 'haz'], no_child=1, C=[[0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 2]
 [1 2]], p=[0.001 0.999 0.01  0.99  0.1   0.9  ]]


In [16]:
del sys.modules[cpm]
from BNS_JT import cpm

KeyError: <module 'BNS_JT.cpm' from 'C:\\Users\\jb622s\\git\\BNS-JT\\BNS_JT\\cpm.py'>

In [23]:
cpms_inf = {x: cpms[x] for x in vars_inf1}
cond_vars = ['haz', 'xs0']
oth_vars = [v for v in vars_inf1 if v not in cond_vars] # other variables
oth_cpms = {v: cpms_inf[v] for v in oth_vars}
sys_var = 'h0' # must be one (FUTHER RESEARCH REQUIRED: there is no efficient way yet to compute a joint distribution of more than one system event)
VE_vars = [v for v in vars_inf1 if v not in cond_vars and v != sys_var]
VE_cpms = {v: cpms_inf[v] for v in VE_vars}

M_cvars = cpm.prod_cpms( [cpms[v] for v in cond_vars] )
m1 = M_cvars.get_subset([0])

VE_cpms_m1 = cpm.condition( VE_cpms, m1.variables, m1.C[0] )
sys_cpm_m1 = cpm.condition(cpms_inf[sys_var], m1.variables, m1.C[0] )

m_m1 = cpm.variable_elim(  )

In [30]:
isin = cpm.isinscope([vars['xs0']], cpms)
print(isin)

[[False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
